/**
 * <p>Generated classes for implementing the Mount (version 1) and NFS (version 2) protocols.</p>
 *
 * <p>These classes are generated by the {@code rpcgen} plugin of the Remote Tea project to create, transmit,
 * receive, and parse messages defined for the protocols needed to access data from the NFSv2 servers running
 * in players. They are not really meant for human consumption.</p>
 *
 * <p>These classes are used by {@link org.deepsymmetry.cratedigger.FileFetcher}, which provides the API for
 * taking advantage of them.</p>
 *
 * <p>The RPC source code for these classes, which is much more readable than the classes themselves,
 * can be found <a href="https://github.com/Deep-Symmetry/crate-digger/tree/master/src/main/rpc"
 *   target="_blank">here</a>.</p>
 *
 * @author  James Elliott
 */
package org.deepsymmetry.cratedigger.rpc;