/**
 * <p>Generated classes for parsing rekordbox database export and track analysis files, along with support
 * classes.</p>
 *
 * <p>Most of these classes are generated by the Kaitai Struct Compiler project to parse the files containing track and
 * artwork information. They are not really meant for human consumption.
 * The exception is {@link org.deepsymmetry.cratedigger.pdb.UnmaskSongStructureTag}, which is used to undo
 * the weak “encryption” which masks most of the content of this tag, and has to happen as part of the parsing
 * of the tag. This is a <a href="https://doc.kaitai.io/user_guide.html#custom-process" target="_blank">custom
 * processing function</a> for the generated classes to invoke.</p>
 *
 * <p>The generated classes are used by {@link org.deepsymmetry.cratedigger.Database}, which provides the API for
 * taking advantage of them.</p>
 *
 * <p>The Kaitai Struct source code for these classes, which is much more readable than the classes themselves,
 * can be found <a href="https://github.com/Deep-Symmetry/crate-digger/tree/master/src/main/kaitai"
 *   target="_blank">here</a>.</p>
 *
 * @author  James Elliott
 */
package org.deepsymmetry.cratedigger.pdb;