/**
 * <p>Generated classes for parsing rekordbox database export and track analysis files.</p>
 *
 * <p>These classes are generated by the Kaitai Struct Compiler project to parse the files containing track and
 * artwork information. They are not really meant for human consumption.</p>
 *
 * <p>These classes are used by {@link org.deepsymmetry.cratedigger.Database}, which provides the API for
 * taking advantage of them.</p>
 *
 * <p>The Kaitai Struct source code for these classes, which is much more readable than the classes themselves,
 * can be found <a href="https://github.com/Deep-Symmetry/crate-digger/tree/master/src/main/kaitai"
 *   target="_blank">here</a>.</p>
 *
 * @author  James Elliott
 */
package org.deepsymmetry.cratedigger.pdb;