[[analysis-files]]
= Analysis Files
James Elliott <james@deepsymmetry.org>
:icons: font
:experimental:

When rekordbox analyzes tracks there is some data that is too big to
fit in the database itself. We have already seen some of that (the
album art images, and of course the track audio is left in the
filesystem as well). The other analysis data is organized into “anlz”
files, whose path can be found in the DeviceSQL string pointed to by
index 14 in the string offsets found at the end of the corresponding
<<exports#track-rows,track row>>. These files have names like `ANLZ0001.DAT`
and their structure is described in this section.

The files are “tagged type” files, where there is an overall file
header section, and then each entry in the file has its own header
which identifies the type and length of that section.

Later player hardware added support for things like colored and
more-detailed waveforms. Apparently these were deemed too large to fit
in the `.DAT` files (probably due to memory limitations of the older
players downloading those files), so another file was introduced,
which shares the same base filename as the `.DAT` file, but uses an
extension of `.EXT` instead. Both kinds of file share the same
structure, but different sets of tags can be found in each.

== Analysis File Header

For some reason the analysis files store their numbers in big-endian
byte order, the opposite of the `export.pdb` database file. Field
names used in the byte field diagrams match the IDs assigned to them
in the
https://github.com/Deep-Symmetry/crate-digger/blob/master/src/main/kaitai/rekordbox_anlz.ksy[Kaitai
Struct specification], unless that is too long to fit, in which case a
subscripted abbreviation is used, and the text will mention the actual
struct field name.

The file itself starts with the four-character code `PMAI` that
identifies its format. This file format identifier is followed a
four-byte value, __len_header__ (at bytes{nbsp}``04``-`07`) that
specifies the length of the file header in bytes. This is followed by
another four-byte value, __len_file__, at bytes{nbsp}``08``-`0b` that
specifies the length of the whole file in bytes:

.Analysis file structure.
[bytefield]
----
(draw-column-headers)
(draw-box (text "PMAI" :hex) {:span 4})
(draw-box (text "len_header" :math) {:span 4})
(draw-box (text "len_file" :math) {:span 4})
(draw-related-boxes (repeat 16 nil))
(draw-gap "Tagged sections")
(draw-bottom)
----

The header seems to usually be `1c` bytes long, though we do not yet
know the purpose of any of the header values that come after
__len_file__. After the header, the file consists of a series of
tagged sections, each with their own four-character code identifying
the section type, followed by a header and the section content. This
overall structure is illustrated in the above diagram, and the
structure of the known tag types is described next.

== Analysis File Sections

The structure of each tagged section has an “envelope” that can be
understood even if the internal structure of the section is unknown,
making it easy to navigate through the file looking for the section
you need. This structure is very similar to the file itself, and is
illustrated below.

.Tagged section structure.
[bytefield]
----
(draw-column-headers)
(draw-box (text "fourcc" :math) {:span 4})
(draw-box (text "len_header" :math) {:span 4})
(draw-box (text "len_tag" :math) {:span 4})
(draw-gap "Tag-specific content")
(draw-bottom)
----

Every section begins with a four-character code, _fourcc_, identifying
its specific structure and content, as described in the sections
below. This is followed by a four-byte value, __len_header__, which
specifies how many bytes there are in the section header, and another
four-byte value, __len_tag__, which specifies the length of the entire
tagged section (including the header), in bytes. This value can be
added to the address of the start of the tag to find the start of the
next tag.

There is not much value to __len_header__. If you study the structure
of each type of tagged section, you can see some sense of where the
“header-like stuff ” ends, and “content-like stuff” begins, and this
seems to line up with the value of __len_header__. But because there
are important values in each tag’s header, and those always start
immediately after __len_tag__, it is simply easier to ignore the value
of __len_header__, and model the tag body as beginning at byte `0c` of
the tag. To show where the boundary occurs, in the diagrams that
follow, values that fall inside the byte range of the header are
colored yellow.

=== Beat Grid Tag

This kind of section holds a list of all beats found within the track,
recording their bar position, the time at which they occur, and the
tempo at that point. It is identified by the four-character code
`PQTZ`, which may stand for “Pioneer Quantization”. It has the
structure shown below. __len_header__ is 18. The tag-specific
content starts with two unknown values, although Mr. Flesniak says
that _unknown~2~_ seems to always have the value `00800000`.

.Beat Grid tag.
[bytefield]
----
include::example$tag_shared.edn[]
(draw-tag-header "PQTZ")
(draw-box (text "unknown" :math [:sub 1]) [:bg-yellow {:span 4}])
(draw-box (text "unknown" :math [:sub 2]) [:bg-yellow {:span 4}])
(draw-box (text "len_beats" :math) [:bg-yellow {:span 4}])
(draw-gap "Beat entries")
(draw-bottom)
----

__len_beats__ at bytes{nbsp}``14``-`17` specifies the number of beats
were found in the track, and thus the number of beat entries that will
be present in this section. The beat entries come next, and each has
the following structure:

.Beat Grid beat.
[bytefield]
----
(def boxes-per-row 8)
(def left-margin 1)
(draw-column-headers)
(draw-box (text "b" :math [:sub "num"]) {:span 2})
(draw-box (text "tempo" :math) {:span 2})
(draw-box (text "time" :math) {:span 4})
----

Each beat entry is eight bytes long. It starts with _beat_number_, a
two-byte number (abbreviated _b~num~_ in the byte field diagram above)
which specifies where the beat falls within its measure. So the value
is always 1, 2, 3, or 4. This is followed by a two-byte _tempo_ value,
which records the track tempo at the point where this beat occurs, in
beats per minute multiplied by 100 (to allow a precision of
stem:[\frac{1}{100}] BPM). Finally, there is a four-byte _time_ value,
which specifies the time at which this beat would occur, in
milliseconds, when playing the track at its normal speed.

As noted above, there will be as many beat entries as __len_beats__
specifies. They continue to the end of the tag.

[[cue-list]]
=== Cue List Tag

This kind of section holds either a list of ordinary memory points and
loops, or a list of hot cues and hot loops. It is identified by the
four-character code `PCOB`, and has the structure shown below.
__len_header__ is `18`.

NOTE: Since the release of the Nexus 2 series of players, there is a
newer tag available that contains more information and supports more
hot cues, so you should check for that before loading this tag. See
<<extended-cue-list>> for details.

.Cue List tag.
[bytefield]
----
include::example$tag_shared.edn[]
(draw-tag-header "PCOB")
(draw-box (text "type" :math) [:bg-yellow {:span 4}])
(draw-box (text "unk" :math) [:bg-yellow {:span 2}])
(draw-box (text "len" :math [:sub "cues"]) [:bg-yellow {:span 2}])
(draw-box (text "memory_count" :math) [:bg-yellow {:span 4}])
(draw-gap "Cue entries")
(draw-bottom)
----

The _type_ value at bytes{nbsp}``0c``-`0f` determines whether this
section holds memory points (if _type_ is 0) or hot cues (if _type_ is
1). The number of cue entries present in the section is reported in
_len~cues~_ at bytes{nbsp}``12``-`13`, and we don’t yet know the
meaning of _unk_ at bytes{nbsp}``10``-`11` or __memory_count__ at
bytes{nbsp}``14``-`17`. The remainder of the section, from
byte{nbsp}``18`` through __len_tag__ holds the cue entries themselves,
with the following structure:

.Cue List entry.
[bytefield]
----
include::example$tag_shared.edn[]
(draw-tag-header "PCPT" "len_entry")
(draw-box (text "hot_cue" :math) [:bg-yellow {:span 4}])
(draw-box (text "status" :math) [:bg-yellow {:span 4}])
(draw-box (text "unknown" :math [:sub 1]) [:bg-yellow {:span 4}])
(draw-box (text "o" :math [:sub "first"]) [:bg-yellow {:span 2}])
(draw-box (text "o" :math [:sub "last"]) [:bg-yellow {:span 2}])
(draw-box (text "t" :math))
(draw-box (text "unknown" :math [:sub 2]) {:span 3})
(draw-box (text "time" :math) {:span 4})
(draw-box (text "loop_time" :math) {:span 4})
(draw-related-boxes (repeat 16 nil))
----

Each cue entry is `38` bytes long. It is structured as its own
miniature tag for unknown reasons, starting with the four-character
code `PCPT` (Pioneer Cue Point?), and its own internal four-byte
__len_header__ and __len_entry__ values (`1c` and `38` respectively).

If the cue is an ordinary memory point, __hot_cue__ at
bytes{nbsp}``0c``-`0f` will be zero, otherwise it identifies the
number of the hot cue that this entry represents (Hot Cue A is number
1, B is 2, and so on). The __status__ value at bytes{nbsp}``10``-`13`
seems to be a deletion indicator; if it is zero, the entry is ignored.
Cues which the players pay attention to have the value 1 here.

The next four bytes have an unknown purpose, but seem to always have
the value `00100000`. They are followed by two two-byte values, which
seem to be for sorting the cues in the proper order in some strange
way. __order_first__ at bytes{nbsp}``1a``-`1b` (labeled _o~first~_ in
the diagram) has the value `ffff` for the first cue, `0000` for the
second, then 2, 3 and on. __order_last__ at bytes{nbsp}``1a``-`1b`
(labeled _o~last~_) has the value 1 for the first cue, 2 for the
second, and so on, but `ffff` for the last. It would seem that the
cues could be perfectly well sorted by just one of these fields, or
indeed, by their _time_ values.

The first “non-header” field is _type_ at byte{nbsp}``1c`` (labeled
_t_ in the diagram), and it specifies whether the entry records a
simple position (if it has the value 1) or a loop (if it has the value
2). The next three bytes have an unknown purpose, but seem to always
have the value `0003e8`, or decimal 1000.

The value _time_ at bytes{nbsp}``20``-`23` records the position of the
cue within the track, as a number of milliseconds (representing when
the cue would occur if the track is being played at normal speed). If
_type_ is 2, meaning that this cue stores a loop, then __loop_time__
at bytes{nbsp}``24``-`27` stores the track time in milliseconds at
which the player should loop back to _time_.

We do not know what, if anything, is stored in the remaining bytes of
the cue entry.


[[extended-cue-list]]
=== Extended (nxs2) Cue List Tag

This is a variation of the Cue List Tag <<cue-list,just described>>
that was introduced with the Nexus 2 players to add support for more
than three hot cues with custom color assignments, as well as
DJ-assigned comment text for each hot cue and memory point. It also
contains the information present in the standard Cue List Tag, so you
only need to read one set or the other.
https://github.com/Deep-Symmetry/beat-link#beat-link[Beat Link] tries
to use the extended tags if they are available, and falls back to
using the older ones if they are not.

Just like the older tag, this kind of section holds either a list of
ordinary memory points and loops, or a list of hot cues and hot loops.
It is identified by the four-character code `PCO2`, and has the
structure shown below. __len_header__ is `14`.

.Extended (nxs2) Cue List tag.
[bytefield]
----
include::example$tag_shared.edn[]
(draw-tag-header "PCO2")
(draw-box (text "type" :math) [:bg-yellow {:span 4}])
(draw-box (text "len" :math [:sub "cues"]) [:bg-yellow {:span 2}])
(draw-box 0 [:bg-yellow {:span 2}])
(draw-gap "Cue entries")
(draw-bottom)
----

The _type_ value at bytes{nbsp}``0c``-`0f` determines whether this
section holds memory points (if _type_ is 0) or hot cues (if _type_ is
1). The number of cue entries present in the section is reported in
_len~cues~_ at bytes{nbsp}``10``-`11`, and we don’t yet know the
meaning of the remaining two header bytes. The remainder of the
section, from byte{nbsp}``14`` through __len_tag__ holds the cue
entries themselves, with the following structure:

.Extended (nxs2) Cue List entry.
[bytefield]
----
include::example$tag_shared.edn[]
(draw-tag-header "PCP2" "len_entry")
(draw-box (text "hot_cue" :math) [:bg-yellow {:span 4}])
(draw-box (text "t" :math))
(draw-box (text "unknown" :math [:sub 1]) {:span 3})
(draw-box (text "time" :math) {:span 4})
(draw-box (text "loop_time" :math) {:span 4})
(draw-related-boxes (repeat 12 nil))

(draw-box (text "len_comment" :math) {:span 4})
(draw-gap "comment" {:min-label-columns 4})
(draw-box (text "c" :math))
(draw-box (text "r" :math))
(draw-box (text "g" :math))
(draw-box (text "b" :math))
(draw-related-boxes (repeat 20 nil))
----

Each extended cue entry has a variable length. It is structured as its
own miniature tag, starting with the four-character code `PCP2`, and
its own internal four-byte __len_header__ and __len_entry__ values.
While __len_header__ has the fixed value `10`, __len_entry__ is needed to
determine the length of the entry, so the beginning of the next one
can be located.

If the cue is an ordinary memory point, __hot_cue__ at
bytes{nbsp}``0c``-`0f` will be zero, otherwise it identifies the
number of the hot cue that this entry represents (Hot Cue A is number
1, B is 2, and so on).

The _status_ flag and mysterious sort order values present in the
older cue list entry header are simply absent here.

The first “non-header” field is _type_ at byte{nbsp}``10`` (labeled
_t_ in the diagram), and it specifies whether the entry records a
simple position (if it has the value 1) or a loop (if it has the value
2). The next three bytes have an unknown purpose, but seem to always
have the values `0003e8`, or decimal 1000.

The value _time_ at bytes{nbsp}``14``-`17` records the position of the
cue within the track, as a number of milliseconds (representing when
the cue would occur if the track is being played at normal speed). If
_type_ is 2, meaning that this cue stores a loop, then __loop_time__
at bytes{nbsp}``18``-`1b` stores the track time in milliseconds at
which the player should loop back to _time_.

The next twelve bytes have an unknown purpose, but seem to have the
value `00`, except for the second byte which seems to have the value
`10`. They are followed by __len_comment__, which contains the length,
in bytes, of the _comment_ field which immediately follows it. If
__len_comment__ has a non-zero value, _comment_ will hold the text of
the comment, encoded as a UTF-16 Big Endian string with a trailing
`NUL` (`0000`) character. So the length will always be even, and (when
non-zero) always at least 4 (a one character comment followed by the
trailing `NUL`).

Immediately after _comment_ (in other words, starting __len_comment__
+ `1c` past the start of the entry) there are four one-byte values
containing color information. __color_code__ (labeled _c_ in the
diagram) appears to be a code identifying the color with which
rekordbox displays the cue, by looking it up in a table. There have
been sixteen codes identified, and their corresponding RGB colors can
be found by looking at the
https://github.com/Deep-Symmetry/beat-link/blob/v0.6.1/src/main/java/org/deepsymmetry/beatlink/data/CueList.java#L457-L509[`findRecordboxColor`
static method] in the Beat Link library’s `CueList` class. The next
three bytes, __color_red__ (labeled _r_), __color_green__ (labeled
_g_), and __color_blue__ (labeled _b_), make up an RGB color
specification which is similar, but not identical, to the color that
rekordbox displays. We believe these are the values used to illuminate
the RGB LEDs in a player that has loaded the cue. When no color is
associated with the cue, all four of these bytes have the value `00`.

We do not know what, if anything, is stored in the remaining bytes of
the tag.

=== Path Tag

This kind of section holds the file path of the audio file for which
the track analysis was performed. It is identified by the
four-character code `PPTH` and has the structure shown below.
__len_header__ is `10`.

.Path tag.
[bytefield]
----
include::example$tag_shared.edn[]
(draw-tag-header "PPTH")
(draw-box (text "len_path" :math) [:bg-yellow {:span 4}])
(draw-gap (text "path" :math))
(draw-bottom)
----

__len_path__ at bytes{nbsp}``0c``-`0f` holds the length of the file
path value, which makes up the entire tag body. _path_, which starts
at byte{nbsp}``10``, is a <<exports#devicesql-strings,DeviceSQL
string>>.

=== VBR Tag

This kind of section has not yet been explained, but it is believed to
hold an index allowing rapid seeking to particular times within
variable-bit-rate tracks. (Without such a structure, it would be
necessary to scan the entire file from the beginning to find a frame
starting at a particular time, which would be too slow for jumping to
memory points or hot cues deep within the track.) What is known of the
structure is shown below. The four-character code that identifies this
type of section is `PVBR` and __len_header__ is `10`.

.VBR tag.
[bytefield]
----
include::example$tag_shared.edn[]
(draw-tag-header "PVBR")
(draw-box (text "unknown" :math [:sub 1]) [:bg-yellow {:span 4}])
(draw-gap (text "unknown" :math [:sub 2]))
(draw-bottom)
----

=== Waveform Preview Tag

This kind of section holds a fixed-width monochrome preview of the
track waveform, displayed above the touch strip on original nexus
players, providing a birds-eye view of the current playback position,
and supporting direct needle jump to specific track sections. It is
identified by the four-character code `PWAV` and has the structure
shown below. __len_header__ is `14`.

[[waveform-preview-diagram]]
.Waveform Preview tag.
[bytefield]
----
include::example$tag_shared.edn[]
(draw-tag-header "PWAV")
(draw-box (text "len_preview" :math) [:bg-yellow {:span 4}])
(draw-box (text "unknown" :math) [:bg-yellow {:span 4}])
(draw-gap (text "data" :math))
(draw-bottom)
----

The purpose of the header bytes{nbsp}``10``-`13` is unknown; they
always seem to have the value `00100000`. The waveform preview data
begins at byte{nbsp}``14`` and is 400 (decimal) bytes long. Each byte
encodes one vertical pixel-wide column of the waveform preview. The
height of the column is represented by the five low-order bits of the
byte (so it can range from 0 to 31 pixels high), and the whiteness of
the segment is represented by the three high-order bits. Segments with
higher values in these three bits are drawn in a less saturated
(whiter) shade of blue.

=== Tiny Waveform Preview Tag

This kind of section holds an even smaller fixed-width monochrome
preview of the track waveform, which seems to be displayed on the
CDJ-900. It is identified by the four-character code `PWV2` but
otherwise has the same structure as the larger waveform preview tags
shown <<waveform-preview-diagram,above>>. __len_header__ is still
`14`, and header bytes{nbsp}``10``-`13` also seem to have the value
`00100000`. The waveform preview data begins at byte `14` and is 100
(decimal) bytes long. Each byte encodes one vertical pixel-wide column
of the waveform preview. The height of the column is represented by
the four low-order bits of the byte (so it can only range from 0 to 15
pixels high), and no other bits are used.

include::partial$Footer.adoc[]
