= Database Exports
James Elliott <james@deepsymmetry.org>

== Background

The files written to external media by rekordbox for use in player hardware contain a wealth of information that can be used in place of queries to the `remotedb` server on the players, which is important because they can be obtained from the players’ NFS servers, even if there are four players in use sharing the same media.
Under those circumstances, `remotedb` queries are impossible.
This document shares what has been learned so far about the files, and how to interpret them.

== Database Exports

The starting point for finding track metadata from a player is the database export file, which can be found within rekordbox media at the following path:

----
/PIONEER/rekordbox/export.pdb
----

(If you are using the
https://deepsymmetry.org/cratedigger/apidocs/org/deepsymmetry/cratedigger/FileFetcher.html#fetch(java.net.InetAddress,java.lang.String,java.lang.String,java.io.File)[Crate Digger `FileFetcher`] to request this file, use that path as the `filePath` argument, and use a `mountPath` value of `/B/` if you want to read it from the SD slot, or `/C/` to obtain it from the USB slot).

NOTE: Newer players also support an additional database with the filename `exportExt.pdb` in the same location, which holds a different and smaller set of table types in it.

The file is a relational database format designed to be efficiently used by very low power devices (there were deployments on 16 bit devices with 32K of RAM).
Today you are most likely to encounter it within the Pioneer Professional DJ ecosystem, because it is the format that their rekordbox software uses to write USB and SD media which can be mounted in DJ controllers and used to play and mix music.

The file consists of a series of fixed size pages.
The first page contains a file header which defines the page size and the locations of database tables of different types, by the index of their first page.
The rest of the pages consist of the data pages for all the tables identified in the header.

Each table is made up of a series of rows which may be spread across any number of pages.
The pages start with a header describing the page and linking to the next page.
The rest of the page is used as a heap: rows are scattered around it, and located using an index structure that builds backwards from the end of the page.
Each row of a given type has a fixed size structure which links to any variable-sized strings by their offsets within the page.

As changes are made to the table, some records may become unused, and there may be gaps within the heap that are too small to be used by other data.
There is a bit map in the row index that identifies which rows are actually present.
Rows that are not present must be ignored: they do not contain valid (or even necessarily well-formed) data.

The majority of the work in reverse-engineering this format was performed by https://github.com/henrybetts/Rekordbox-Decoding[Henry Betts] and https://github.com/flesniak/python-prodj-link[Fabian Lesniak], to whom I am hugely grateful.
More recently, https://github.com/voidc[Dominik Stolz (@voidc)] figured out what was in `exportExt.pdb` files.

[#file-header]
=== File Header

Unless otherwise stated, all multibyte numbers in the file are stored in little-endian byte order.
Field names used in the byte field diagrams match the IDs assigned to them in the https://github.com/Deep-Symmetry/crate-digger/blob/master/src/main/kaitai/rekordbox_pdb.ksy[Kaitai Struct specification],footnote:[http://kaitai.io] unless that is too long to fit, in which case a subscript abbreviation is used, and the text will mention the actual struct field name.

.Numbers in this document
****
Values within packets, packet lengths, and byte offsets are all shown in hexadecimal in `code` font.
Other numbers are in normal body text font and are decimal.
****

The first page begins with the file header, shown below.
The header starts with four zero bytes, followed by a four-byte integer, __len_page__ at byte `04`, that establishes the size of each page (including this first one), in bytes.
This is followed by another four-byte integer, __num_tables__ at byte `08`, which reports the number of different tables that are present in the file.
Each table will have a table pointer entry in the “Table pointers” section of the file header, described below, that identifies and locates the table.

.File header.
[bytefield]
----
(draw-column-headers)
(draw-related-boxes (repeat 4 0))
(draw-box (text "len_page" :math) {:span 4})
(draw-box (text "num_tables" :math) {:span 4})
(draw-box (text "next" :math [:sub "u"]) {:span 4})
(draw-box (text "unknown" :math) {:span 4})
(draw-box (text "sequence" :math) {:span 4})
(draw-related-boxes (repeat 4 0))
(draw-gap "Table Pointers")
(draw-bottom)
----

The four-byte integer _next~u~_ at byte `0c` has an unknown purpose, but Mr. Lesniak named it `next_unused_page` and said “Not used as any `empty_candidate`, points past the end of the file.”
The four-byte integer _sequence_, at byte `14`, was described “Always incremented by at least one, sometimes by two or three.” and I assume this means it reflects a version number that rekordbox updates when synchronizing to the exported media.

Finally, there is another series of four zero bytes, and then the header ends with the list of table pointers which begins at byte `1c`. There are as many of these as specified by __num_tables__, and each has the following structure:

.Table pointer.
[bytefield]
----
(def left-margin 1)
(draw-column-headers)
(draw-box (text "type" :math) {:span 4})
(draw-box (text "empty" :math [:sub "c"]) {:span 4})
(draw-box (text "first_page" :math) {:span 4})
(draw-box (text "last_page" :math) {:span 4})
----

Each Table Pointer is a series of four four-byte integers. The first, _type_, identifies the type of table being defined.
The known table types are shown below.
The second value, at byte `04` of the table pointer, was called __empty_candidate__ by Mr. Lesniak.
It may link to a chain of empty pages if the database is ever garbage collected, but this is speculation on my part.

[#table-types]
.Table types present in `export.pdb` files.
[cols=">1m,<2,<8"]
|===
|Type |Name |Meaning

|00 |tracks |<<track-rows,Track metadata>>: title, artist, genre, artwork ID, playing time, etc.
|01 |genres |<<genre-rows,Musical genres>>, for reference by tracks and searching.
|02 |artists |<<artist-rows,Artists>>, for reference by tracks and searching.
|03 |albums |<<album-rows,Albums>>, for reference by tracks and searching.
|04 |labels |<<label-rows,Music labels>>, for reference by tracks and searching.
|05 |keys |<<key-rows,Musical keys>>, for reference by tracks, searching, and key matching.
|06 |colors |<<color-rows,Color labels>>, for reference by tracks and searching.
|07 |playlist_tree |Holds the hierarchical <<playlist-tree-rows,tree structure>> of playlists and folders grouping them.
|08 |playlist_entries |Links tracks to <<playlist-entry-rows,playlists>>, in the right order.
|0d |artwork |File paths of <<artwork-rows,album artwork>> images.
|10 |columns |Details not yet confirmed.
|11 |history_playlists |Holds the list of <<history-playlist-rows,history playlists>> in the History menu.
|12 |history_entries |Links tracks to <<history-entry-rows,history playlists entries>>, in the right order.
|13 |history |Data used by rekordbox to synchronize history playlists (not yet studied).
|===

[#ext-table-types]
.Table types present in `exportExt.pdb` files.
[cols=">1m,<2,<8"]
|===
|Type |Name |Meaning

|03 |tags |<<tag-rows,Tags>>: can be assigned to tracks for the purpose of categorization.
|04 |tag_tracks |<<tag-track-rows,Tag Tracks>>: holds the associations between tag ids and track ids.
|===

Other than the type, the two important values are __first_page__ at byte `08` and __last_page__ at byte `0c`.
These tell us how to find the table.
They are page indices, where the page containing the file header has index 0, the page with index 1 begins at byte __len_page__, and so on.
In other words, the first page of the table identified by the current table pointer can be found within the file starting at the byte __len_page__ × __first_page__.

The table is a linked list of pages: each page contains the index of the next page after it.
However, you need to keep track of the __last_page__ value for the table, because it tells you not to try to follow the next page link once you reach the page with that index.
(If you do keep going, you will start reading pages of some different table.)
The structure of the table pages themselves are described in the next section.

As far as we know, the remainder of the first page after the table pointers is unused.

=== Table Pages

The table header is followed by the table pages themselves.
These each have the size specified by __len_page__ in the above diagram, and the following structure:

==== Table Page Header

All pages, regardless of type, begin with a common header structure.

.Table Page Header
[bytefield]
----
(draw-column-headers)
(draw-related-boxes (repeat 4 0))
(draw-box (text "page_index" :math) {:span 4})
(draw-box (text "type" :math) {:span 4})
(draw-box (text "next_page" :math) {:span 4})
(draw-box (text "version" :math) {:span 4})
(draw-box (text "unknown" :math [:sub "2"]) {:span 4})
(draw-box (text "row counts") {:span 3})
(draw-box (text "p" :math [:sub "f"]))
(draw-box (text "free" :math [:sub "s"]) {:span 2})
(draw-box (text "used" :math [:sub "s"]) {:span 2})
----

The first four bytes of a table page always seem to be zero.
This is followed by a four-byte value _page_index_ which identifies the index of this page within the list of table pages (the header has index 0, the first actual data page the index 1, and so on).
This value seems to be redundant, because it can be calculated by dividing the offset of the
start of the page by _len_page_, but perhaps it serves as a sanity check.

This is followed by another four-byte value, _type_, which identifies the type of the page, using the values shown in the <<table-types,preceding table>>.
This again seems redundant because the table header which was followed to reach this page also identified the table type, but perhaps it is another sanity check, or an alternate way to tell, when following page links, that you have reached the end of the table you are interested in.
Speaking of which, the next four-byte value, __next_page__, is that link: it identifies the index at which the next page of this table can be found, as long as we have not already reached the final page of the table, as described in <<file-header>>.

This is followed by _version_ which is an incrementing integer updated to the global next value every time any page is edited. Versions of different pages can be used to determine which pages were touched in which order during an export. For example, if a track is exported with a new artist and genre, then Rekordbox may place the genre first (with version N), then the artist (with version N+1), then the track (with version N+3).
This might be used by the history feature, or might be some kind of data integrity mechanism. It is unknown what happens when the 32-bit integer overflows.

We don't know what _unknown~2~_ contains, though it is often/always zero. It may be an extension of _version_ to 64-bits?

The three bytes{nbsp}``8``–``a``, labeled “row counts”, actually contain two non-byte-aligned numbers.
The first 13 bits, __num_row_offsets__ keeps track of how many row offsets have ever been allocated in the heap, even if some of them are no longer valid.
This number only ever increases over time, and can be used to calculate how many row groups are present in the page.
The final 11 bits, __num_rows__, report the number of valid rows that are currently present in the table.footnote:[It is unclear why these two values are packed into three bytes like this.
 We did not understand this structure, and had to rely on clumsy workarounds, until https://github.com/RobinMcCorkell[Robin McCorkell] figured this out in December 2025.]

Byte{nbsp}``1b`` is called __page_flags__ (abbreviated _p~f~_ in the diagram), and it's used to distinguish pages of different types. 
Index pages (which contain pointers to data pages with deleted rows) have a __page_flags__ value of `64`. Data pages which are pointed to by index entries have the value `34`, while data pages which aren't have the value `24`. The value `44` has been observed but its meaning is unknown.
Crate Digger considers a page to be a data page if __page_flags__&``40``{nbsp}={nbsp}`0`.

Bytes{nbsp}``1c``-`1d` are called __free_size__ (abbreviated _free~s~_ in the diagram), and store the amount of unused space in the page heap (excluding the row index which is built backwards from the end of the page); __used_size__ at bytes{nbsp}``1c``-`1d` (abbreviated _used~s~_) stores the number of bytes that are in use in the page heap.

==== Data Pages

Data pages follow the common header with a data-specific header and a heap for row data.

.Data Page Details
[bytefield]
----
(draw-column-headers)
(draw-box (text "u" :math [:sub "5"]) {:span 2})
(draw-box (text "unk" :math [:sub "rows"]) {:span 2})
(draw-box (text "u" :math [:sub "6"]) {:span 2})
(draw-box (text "u" :math [:sub "7"]) {:span 2})
(draw-gap "heap")

(draw-box "row groups" {:span 16 :borders #{:left :right}})
(draw-box "…" [:box-below {:span 2}])

(defn draw-ofs [ns]
  (doseq [n ns]
    (draw-box (text "ofs" :math [:sub n]) {:span 2})))

(draw-ofs (take 3 (reverse (range 19))))
(draw-box (text "row" :math [:sub "pf1"]) {:span 2})
(draw-box (text "pad" :math [:sub "1"]) {:span 2})
(draw-ofs (reverse (range 16)))
(draw-box (text "row" :math [:sub "pf0"]) {:span 2})
(draw-box (text "pad" :math [:sub "0"]) {:span 2})
----

Bytes{nbsp}``0``-`1`, _u~5~_ , are of unclear purpose. Mr. Lesniak labeled them “(0→1: 2).”

Bytes{nbsp}``2``-`3`, labeled __unk~rows~__, hold a value that seems related to the number of rows in the table in an unclear way, but sometimes instead equals `1fff`.

_u~6~_ at bytes{nbsp}``4``-`5` seems to have the value `0000` for data pages.
And Mr. Lesniak describes _u~7~_ at bytes{nbsp}``6``-`7` as “always 0 except 1 for history pages”.

After these header fields comes the page heap.
Rows are allocated within this heap starting at byte `8`.
Since rows can be different sizes, there needs to be a way to locate them.
This takes the form of a row index, which is built from the end of the page backwards, in groups of up to sixteen row pointers along with a bitmask saying which of those rows are still part of the table (they might have been deleted).
The number of row index entries is determined, as described above, by the value of either __num_rows_small__ or __num_rows_large__.

[#row-presence-bits]
The bit mask for the first group of up to sixteen rows, labeled _row~pf0~_ in the diagram (meaning “row presence flags group 0”), is found near the end of the page.
The last two bytes after each row bitmask (for example _pad~0~_ after _row~pf0~_) have an unknown purpose and may always be zero, and the _row~pf0~_ bitmask takes up the two bytes that precede them.
The low-order bit of this value will be set if row 0 is really present, the next bit if row 1 is really present, and so on.
The two bytes before these flags, labeled _ofs~0~_, store the offset of the first row in the page.
This offset is the number of bytes past the end of the page header at which the row itself can be found.
So if row 0 begins at the very beginning of the heap, at byte `28` in the page, _ofs~0~_ would have the value `0000`.

As more rows are added to the page, space is allocated for them in the heap, and additional index entries are added at the end of the heap, growing backwards.
Once there have been sixteen rows added, all the bits in _row~pf0~_ are accounted for, and when another row is added, before its offset entry _ofs~16~_ can be added, another row bit-mask entry _row~pf1~_ needs to be allocated, followed by its corresponding _pad~1~_.
And so the row index grows backwards towards the rows that are being added forwards, and once they are too close for a new row to fit, the page is full, and another page gets allocated to the table.

==== Index Pages

Index pages have a __page_flags__ value of `64`. They follow the common header with an index-specific header and a list of index entries. These entries seem to point to a page which has deleted rows, which would make sense in order to provide a way to find free space when inserting new rows.
It has been observed that the first page of every table is an index page, usually empty if there are no deleted rows yet.

.Index Page Details
[bytefield]
----
(draw-column-headers)
(draw-box (text "u" :math [:sub "a"]) {:span 2})
(draw-box (text "u" :math [:sub "b"]) {:span 2})
(draw-related-boxes [(text "ec" :hex) (text "03" :hex)] {:span 1})
(draw-box (text "next" :math [:sub "o"]) {:span 2})
(draw-box (text "page_index" :math) {:span 4})
(draw-box (text "next_page" :math) {:span 4})
(draw-related-boxes [(text "ff" :hex) (text "ff" :hex) (text "ff" :hex) (text "03" :hex)] {:span 1})
(draw-related-boxes [(text "00" :hex) (text "00" :hex) (text "00" :hex) (text "00" :hex)] {:span 1})
(draw-box (text "num" :math [:sub "e"]) {:span 2})
(draw-box (text "first" :math [:sub "e"]) {:span 2})
(draw-gap "Index Entries")
(draw-bottom)
----

The header of an index page contains several fields whose purpose is not yet fully understood.

The first two bytes are called _unknown~a~_ and they are usually `1fff` or `0001`, although values like `0002` have been observed on tables with a big number of rows.

After that, bytes `2-3` are called _unkown~b~_ and they're usually `1fff` or `0000`, although values like `00b3` have been observed on tables with a big number of rows.

Next comes a 2-byte magic value `03ec`. 

__next_offset__ (bytes `6-7`, abbreviated _next~o~_) specifies the byte offset of where to insert the next index entry. Relative to the start of index entries, usually zero for empty pages. 

Bytes `8-11` and `12-15` are _page_index_ and __next_page__, and they reflect the values with the same name that are found in the common page header.

The two following 32-bit fields contain another magic value `03ffffff` and zeros `00000000`.

The __num_entries__ field at bytes `24-25` (abbreviated _num~e~_) indicates how many index entries are present in the page. Field __first_empty__ at bytes `26-27` (abbreviated _first~e~_) points to the first empty index entry, and is `1fff` if there are none. An empty index entry just contains `1ffffff8`.

.Index Entry
[bytefield]
----
(def box-width 30)
(def boxes-per-row 32)
(def left-margin 1)

;; Create a list of 32 labels, from "31" down to "0"
(def bit-labels (mapv str (reverse (range 32))))

;; Use your custom labels for the headers
(draw-column-headers {:labels bit-labels})

;; Example of drawing 32 empty boxes
(draw-box (text "page_index" :math [:sub "28-0"]) {:span 29})
(draw-box (text "index_flags" :math) {:span 3})
----

Each entry is a four-byte value. As we have said above, an index entry of `1ffffff8` indicates an empty slot.
Otherwise, the entry is a bitfield that contains a page index and some flags.

Bits `31-3` are a page index (i.e. the page that is pointed to by this index entry) but without the 3 most significative bits. Bits `0-2` (called `index_flags`) have unknown purpose, and their most common value is `000`.

== Table Rows

The structure of the rows themselves is determined by the _type_ of the table, using the values shown in <<table-types,Table types>>.
Unless otherwise noted, these table types and rows appear in `export.pdb` files.

[#album-rows]
=== Album Rows

Album rows hold an album name and ID along with an artist association, with the two structure variants shown below.
The value at bytes bytes{nbsp}``00``-`01` are the _subtype_ and differentiate the two variants.footnote:subtype[The Album, Artist, Tag, and Track tables all use subtypes to determine the size of string offsets, although Track rows seem to always be big enough to require the two-byte offset variant.]
The value `80` is for the short version while `84` is for the long version.
It is followed by a two-byte value Mr. Lesniak called __index_shift__, although I don’t know what that means, and another four bytes of unknown purpose.
But at bytes{nbsp}``08``-`0b` we finally find a value we have a use for: __artist_id__ holds the ID of an artist row associated with this track row.
This is followed by __id__, the ID of this track row itself, at bytes{nbsp}``0c``-`0f`.
We assume that there are index tables somewhere that would let us locate the page and row index of a record given its table type and ID, but we have not yet found and figured them out.

This is followed by four more bytes with unknown meaning, and then the two subtypes diverge, because the remaining values consume a different number of bytes in each variant:

For subtype `80` there is a byte holding the value `03` followed by the final byte in the row, __ofs_name_near__ at byte{nbsp}``15``, a single byte pointer to the track name (labeled _o~n~_ in the <<album-row-near,byte field diagram>>). To find the location of the name, add __ofs_name_near__ bytes to the address of the start of the track row.

If the subtype is `84`, the row is of the second form, so the value `0003` takes up two bytes, followed by a two byte offset, __ofs_name_far__, at bytes{nbsp}``16``–`17` (labeled _o~far~_ in the <<album-row-far,diagram>>).

Which variant occurs seems to also depend on the length of the name (if the string takes more than about 200 bytes, the far name variant is used), so the `84` subtype may occur even if the string itself is placed directly following __ofs_name_far__.

The name itself is encoded in a surprisingly baroque way, explained in <<devicesql-strings>>.

[#album-row-near]
.Album row with nearby name.
[bytefield]
----
(draw-column-headers)
(draw-box 0x80 {:span 2})
(draw-box (text "i" :math [:sub "shift"]) {:span 2})
(draw-box (text "unknown" :math [:sub 2]) {:span 4})
(draw-box (text "artist_id" :math) {:span 4})
(draw-box (text "id" :math) {:span 4})
(draw-box (text "unknown" :math [:sub 3]) {:span 4})
(draw-box 0x03)
(draw-box (text "o" :math [:sub "n"]))
----

[#album-row-far]
.Album row with far name.
[bytefield]
----
(draw-column-headers)
(draw-box 0x84 {:span 2})
(draw-box (text "i" :math [:sub "shift"]) {:span 2})
(draw-box (text "unknown" :math [:sub 2]) {:span 4})
(draw-box (text "artist_id" :math) {:span 4})
(draw-box (text "id" :math) {:span 4})
(draw-box (text "unknown" :math [:sub 3]) {:span 4})
(draw-box 0x03 {:span 2})
(draw-box (text "o" :math [:sub "far"]) {:span 2})
----


[#artist-rows]
=== Artist Rows

Artist rows hold an Artist name and ID, with the structure shown in <<artist-row-near,Artist row with nearby name>> or
<<artist-row-far,Artist row with far name>>.
The _subtype_ value at bytes{nbsp}``00``-`01` determines which variant is used.footnote:subtype[]

If the artist name is short enough and was allocated close enough to the row to be reached by a single
byte offset, _subtype_ has the value `0060`, and the row has the structure in <<artist-row-near,Artist row with nearby name>>.
If the name is larger than about 200 bytes or is too far away for that, _subtype_ has the value `0064` and the row has the structure in <<artist-row-far,Artist row with far name>>.

[#artist-row-near]
.Artist row with nearby name.
[bytefield]
----
(def boxes-per-row 0x0a)
(def left-margin 1)
(draw-column-headers)
(draw-box 0x60 {:span 2})
(draw-box (text "i" :math [:sub "shift"]) {:span 2})
(draw-box (text "id" :math) {:span 4})
(draw-box 0x03)
(draw-box (text "o" :math [:sub "n"]))
----

[#artist-row-far]
.Artist row with far name.
[bytefield]
----
(def boxes-per-row 0x0c)
(def left-margin 1)
(draw-column-headers)
(draw-box 0x64 {:span 2})
(draw-box (text "i" :math [:sub "shift"]) {:span 2})
(draw-box (text "id" :math) {:span 4})
(draw-box 0x03 {:span 2})
(draw-box (text "o" :math [:sub "far"]) {:span 2})
----

In either case, _subtype_ is followed by the unexplained two-byte value found in many row types that Mr. Lesniak called __index_shift__, and then by _id_, the ID of this artist row itself, at bytes{nbsp}``04``-`07`.
After the id, the number 3 is always stored, followed by the offset to the name string.
For subtype `0060`, each of these values take a single byte, and __ofs_name_near__ at byte{nbsp}``09`` (labeled _o~n~_), is the one-byte name offset.
For subtype `0064`, each is stored in two bytes, and the two-byte name offset value __ofs_name_far__ (labeled _o~far~_) is found at bytes{nbsp}``0a``–`0b`.

Whichever name offset is used, it is a pointer to the artist name.
To find the location of the name, add the value of the offset to the address of the start of the artist row itself.
This gives the address of a DeviceSQL string holding the name, with the structure explained in <<devicesql-strings>>.


[#artwork-rows]
=== Artwork Rows

Artwork rows hold an _id_ (which tracks refer to) and the path at which the corresponding album art image file can be found, with the structure shown below.
Note that in this case, the DeviceSQL string _path_ is embedded directly into the row itself, rather than being located elsewhere in the heap through an offset. The structure of the string itself is still as described in <<devicesql-strings>>.

.Artwork row.
[bytefield]
----
(draw-column-headers)
(draw-box (text "id" :math) {:span 4})
(draw-gap (text "path" :math))
(draw-bottom)
----

TIP: The art file pointed to by this path will be the original resolution 80x80 pixel image.
Recent versions of rekordbox will also add a higher resolution image, at 240x240 pixels. Its path can be found by adding the string `_m` right before the file extension.
So for example if the original resolution path is `/a/b/foo.jpg`, the high resolution file can be found at `/a/b/foo_m.jpg`.


[#color-rows]
=== Color Rows

Color rows hold a numeric color _id_ (which controls the actual color displayed on the player interface) at bytes{nbsp}``05``-`06` and a text label or __name__ starting at byte{nbsp}``08`` which is a <<devicesql-strings,DeviceSQL string>> shown in the information panel for tracks that are assigned the color.
The rows have the structure shown below.
There are several bytes in the row that are not yet known to have any meaning.

.Color row.
[bytefield]
----
(draw-column-headers)
(draw-box (text "unknown" :math [:sub 1]) {:span 4})
(draw-box (text "u" :math [:sub 2]))
(draw-box (text "id" :math) {:span 2})
(draw-box (text "u" :math [:sub 3]))
(draw-gap (text "name" :math))
(draw-bottom)
----

Regardless of the names assigned to the colors by the user, the row _id_ values map to the following colors in the user interface of rekordbox and on CDJs:

.Colors displayed.
[cols=">1m,<8"]
|===
|ID |Meaning

|0 |No color
|1 |Pink
|2 |Red
|3 |Orange
|4 |Yellow
|5 |Green
|6 |Aqua
|7 |Blue
|8 |Purple
|===

[#genre-rows]
=== Genre Rows

Genre rows hold a numeric genre _id_ (which tracks can be assigned) at bytes{nbsp}``00``-`03` and a text _name_ starting at byte{nbsp}``04`` which is a <<devicesql-strings,DeviceSQL string>>.
The rows have the structure shown below:

[#genre-label-row]
.Genre or Label row.
[bytefield]
----
(draw-column-headers)
(draw-box (text "id" :math) {:span 4})
(draw-gap (text "name" :math))
(draw-bottom)
----


[#history-playlist-rows]
=== History Playlist Rows

The History menu automatically records playlists of the tracks performed off a particular USB or SD card in a new, numbered playlist each time the media is mounted in a player.
These playlists have names like "HISTORY 001".
This table lists all the history playlists which have been created for the current database, tying their name to an ID which is used to match the <<history-entry-rows>> that make up the playlist for the corresponding performance.

The rows are much simpler than the general-purpose hierarchical playlists described <<playlist-tree-rows,below>>.
They hold only a numeric _id_ at bytes{nbsp}``00``-`03` and a text _name_ starting at byte{nbsp}``04`` which is a <<devicesql-strings,DeviceSQL string>>.

.History Playlist row.
[bytefield]
----
(draw-column-headers)
(draw-box (text "id" :math) {:span 4})
(draw-gap (text "name" :math))
(draw-bottom)
----

[#history-entry-rows]
=== History Entry Rows

History entry rows list the tracks that belong to a particular history playlist, and also establish the order in which they were played.
They have a very simple structure, shown below, containing only three values.
The __track_id__ at bytes{nbsp}``00``-`03` identifies the track that was played at this position in the playlist, by corresponding to the _id_ of a row in the <<track-rows,Track table>>.
The __playlist_id__ at bytes{nbsp}``04``-`07` identifies the history playlist to which it belongs, by corresponding to the __id__ of a row in the <<history-playlist-rows,History Playlist table>>.
The __entry_index__ at bytes{nbsp}``08``-`0b` specifies the position within the playlist at which this entry belongs.


.History Entry row.
[bytefield]
----
(def boxes-per-row 0x0c)
(def left-margin 1)
(draw-column-headers)
(draw-box (text "track_id" :math) {:span 4})
(draw-box (text "playlist_id" :math) {:span 4})
(draw-box (text "entry_index" :math) {:span 4})
----


[#key-rows]
=== Key Rows

Key rows represent musial keys.
They hold a numeric _id_ (which tracks can be assigned) at bytes{nbsp}``00``-`03` and a text _name_ starting at byte{nbsp}``08`` which is a <<devicesql-strings,DeviceSQL string>>.
(There seems to be a second copy of the ID at bytes{nbsp}``04``-`07`.)
The rows have the structure shown below:

[#key-row]
.Key row.
[bytefield]
----
(draw-column-headers)
(draw-box (text "id" :math) {:span 4})
(draw-box (text "id2" :math) {:span 4})
(draw-gap (text "name" :math))
(draw-bottom)
----

[#label-rows]
=== Label Rows

Label rows represent record labels.
They hold a numeric genre _id_ (which tracks can be assigned) at bytes{nbsp}``00``-`03` and a text_name_ starting at byte{nbsp}``04`` which is a <<devicesql-strings,DeviceSQL string>>.
The rows have the structure shown in <<genre-label-row,Genre or Label row>>, above.

[#playlist-tree-rows]
=== Playlist Tree Rows

Playlist tree rows are used to organize the hierarchical structure of the playlist menu.
There is probably an index somewhere that makes it possible to find the right rows directly when loading a playlist, but we have not yet figured out how indices work in DeviceSQL databases, so Crate Digger simply reads all the rows and builds its own in-memory index of the tree.

Playlist tree rows can either represent a playlist “folder” which contains other folders and playlists, or a regular playlist which holds only tracks.
The rows are identified by an _id_ at bytes{nbsp}``0c``-`0f`, and also contain a __parent_id__ at bytes{nbsp}``00``-`03` which is how the hierarchical structure is represented: the contents of a folder are the other rows in this table whose __parent_id__ folder is equal to the _id_ of the folder.

Similarly, the tracks that make up a regular playlist are the <<playlist-entry-rows>> whose __playlist_id__ is equal to this row’s _id_.

Each playlist tree row also has a text _name_ starting at byte{nbsp}``14`` which is a <<devicesql-strings,DeviceSQL string>> displayed when navigating the hierarchy, a __sort_order__ indicator at bytes{nbsp}``08``-`0b` (this may be the same value used to select sort orders when requesting menus using the dbserver protocol, shown in the xref:djl-analysis:ROOT:track_metadata.adoc#alternate-track-sort-orders[packet analysis], but this has not yet been confirmed), and a value that specifies whether the row defines a folder or a playlist.
In the Kaitai Struct definition, this value is called __raw_is_folder__, is found at bytes{nbsp}``10``-`13`, and has a non-zero value for folders.
For convenience, the struct also defines a derived value, __is_folder__, which is a boolean.

The rows have the following structure:

.Playlist Tree row.
[bytefield]
----
(draw-column-headers)
(draw-box (text "parent_id" :math) {:span 4})
(draw-box (text "unknown" :math) {:span 4})
(draw-box (text "sort_order" :math) {:span 4})
(draw-box (text "id" :math) {:span 4})
(draw-box (text "raw_is_folder" :math) {:span 4})
(draw-gap (text "name" :math))
(draw-bottom)
----

[#playlist-entry-rows]
=== Playlist Entry Rows

Playlist entry rows list the tracks that belong to a particular playlist, and also establish the order in which they should be played.
They have a very simple structure, shown below, containing only three values.
The __entry_index__ at bytes{nbsp}``00``--`03` specifies the position within the playlist at which this entry belongs.
The __track_id__ at bytes{nbsp}``04``--`07` identifies the track to be played at this position in the playlist, by corresponding to the _id_ of a row in the <<track-rows,Track table>>, and the __playlist_id__ at bytes{nbsp}``08``--`0b` identifies the playlist to which it belongs, by corresponding to the __id__ of a row in the <<playlist-tree-rows,Playlist Tree>>.

.Playlist Entry row.
[bytefield]
----
(def boxes-per-row 0x0c)
(def left-margin 1)
(draw-column-headers)
(draw-box (text "entry_index" :math) {:span 4})
(draw-box (text "track_id" :math) {:span 4})
(draw-box (text "playlist_id" :math) {:span 4})
----

[#tag-rows]
=== Tag Rows

NOTE: These are present in `exportExt.pdb` files, _not_ the main `export.pdb` database.

Tags provide a flexible way for DJs to categorize tracks, supported by the “My Tags” tab within rekordbox.
Tags have names, and can be assigned to any number of tracks.
Tags themselves can be grouped into categories, which are stored in the same table.

Tag rows have the structure shown in <<tag-row-near,Tag row with nearby name>> or
<<tag-row-far,Tag row with far name>>.
The _subtype_ value at bytes{nbsp}``00``-`01` determines which variant is used.footnote:subtype[]

If the tag name is short enough and was allocated close enough to the row to be reached by a single
byte offset, _subtype_ has the value `0680`, and the row has the structure in <<tag-row-near,Tag row with nearby name>>.
If the name is larger than about 200 bytes or is too far away for that, _subtype_ has the value `0684` and the row has the structure in <<tag-row-far,Tag row with far name>>.

[#tag-row-near]
.Tag row with nearby name.
[bytefield]
----
(draw-column-headers)
(draw-box 0x680 {:span 2})
(draw-box (text "tag_index" :math) {:span 2})
(draw-related-boxes (repeat 8 0))
(draw-box (text "category" :math) {:span 4})
(draw-box (text "category_pos" :math) {:span 4})
(draw-box (text "id" :math) {:span 4})
(draw-box (text "raw_is_category" :math) {:span 4})
(draw-box 0x03)
(draw-box (text "o" :math [:sub "n"]))
(draw-box (text "o" :math [:sub "u"]))
(draw-bottom)
----

[#tag-row-far]
.Tag row with far name.
[bytefield]
----
(draw-column-headers)
(draw-box 0x684 {:span 2})
(draw-box (text "tag_index" :math) {:span 2})
(draw-related-boxes (repeat 8 0))
(draw-box (text "category" :math) {:span 4})
(draw-box (text "category_pos" :math) {:span 4})
(draw-box (text "id" :math) {:span 4})
(draw-box (text "raw_is_category" :math) {:span 4})
(draw-box 0x03 {:span 2})
(draw-box (text "o" :math [:sub "far"]) {:span 2})
(draw-box (text "o" :math [:sub "ufar"]) {:span 2})
(draw-bottom)
----

__tag_index__ at bytes{nbsp}``02``–`03` seems to increment by `20` for each row.
This is followed by another eight bytes of unknown purpose that always seem to be zero.

The __category__ at bytes{nbsp}``0c``–``0f`` holds the ID of the category to which the tag belongs; if this row is itself a category, this field has the value 0.
The __category_pos__ at bytes{nbsp}``10``–``13`` specifies zero-based position at which this tag should be displayed within its category.
If the row represents a category rather than a tag, then this is the zero-based position of the category itself within the category list.

The __id__ at  bytes{nbsp}``14``–``17`` is how the tag or category is referenced in <<tag-track-rows>> or the __category__ field.
Tags seem to have very large _id_ values, while the four categories have fixed `id` values in the range 1--4.

The value of __raw_is_category__ at bytes{nbsp}``18``–``1b`` is non-zero when this row stores a tag category instead of a tag.
It is followed by two bytes of unknown purpose that always seem to have the same values, and a byte that may hold some sort of flags that have not yet been understood.

After the __raw_is_category__, the number 3 is always stored, followed by the offset to the name string, and another string offset with unknown purpose.

For subtype `0680`, each of these values take a single byte, and __ofs_name_near__ at byte{nbsp}``1d`` (labeled _o~n~_), is the one-byte name offset.
__ofs_unknown_near__ at byte{nbsp}``1e`` (labeled _o~u~_), is a one-byte offset to what seems to always be an empty string.

For subtype `0684`, each is stored in two bytes, and the two-byte name offset value __ofs_name_far__ (labeled _o~far~_) is found at bytes{nbsp}``1e``–`1f`.
The offset to the unknown (but seemingly always empty) string (labeled _o~ufar~_) takes the final two bytes.

Whichever name offset is used, it is a pointer to the tag name.
To find the location of the name, add the value of the offset to the address of the start of the tag row itself.
This gives the address of a DeviceSQL string holding the name, with the structure explained in <<devicesql-strings>>.

[#tag-track-rows]
=== Tag Track Rows

NOTE: These are present in `exportExt.pdb` files, _not_ the main `export.pdb` database.

These rows establish the relationship between <<tag-rows,Tags>> and <<track-rows,Tracks>>.

The rows have the following structure:

.Tag Track row.
[bytefield]
----
(draw-column-headers)
(draw-related-boxes (repeat 4 0))
(draw-box (text "track_id" :math) {:span 4})
(draw-box (text "tag_id" :math) {:span 4})
(draw-related-boxes [3 0 0 0])
(draw-bottom)
----

The first four bytes have no known purpose and always seem to be zero.

The __track_id__ at bytes{nbsp}``04``--``07`` identifies the  <<track-rows,Track>> to which a tag has been assigned.
The __tag_id__ at bytes{nbsp}``08``--``0c`` identifies a <<tag-rows,Tag>> the DJ has assigned to this track.

The final four bytes in the row seem to always have the values shown, and have no known purpose.

[#track-rows]
=== Track Rows

Track rows describe audio tracks that can be played from the media export, and provide many details about the music including links to other tables like artists, albums, keys, and others.
They have the structure shown below:

.Track row.
[bytefield]
----
include::example$track_row.edn[]
----

The first two bytes, labeled _subtype_, seem to always have the value `0024`.
As in the other tables which use offset strings,footnote:subtype[] the fact that the `4` bit is set means that the offset size is sixteen bits.
Track rows always have enough string content to need sixteen bit offsets.
They are followed by the unexplained two-byte value found in many row types that Mr. Lesniak
called __index_shift__, and a four-byte value he called _bitmask_, although we do not know what the bits mean.
The value at bytes{nbsp}``08``-`0b`, __sample_rate__, is the first one we have a solid understanding of: it holds the playback sample rate of the audio file, in samples per second (this will be 0 if it is unknown or variable).

Bytes{nbsp}``0c``-`0f` hold the value __composer_id__ which identifies the composer of the track, if known, as a non-zero _id_ value of an <<artist-rows,Artist row>>.
The size of the audio file, in bytes, is found in __file_size__ at bytes{nbsp}``10``-`13`.
This is followed by an unknown four-byte value, _u~2~_, which may be another ID, and two unknown two-byte values, _u~3~_ (about which Mr. Lesniak says “always 19048?”) and _u~4~_ (“always 30967?”).

If there is cover art for the track, there will be a non-zero value in __artwork_id__ (bytes{nbsp}``1c``-`1f`), identifying the _id_ of an <<artwork-rows,Artwork row>>.

If a dominant musical key was identified for the track there will be a non-zero value in __key_id__ (bytes{nbsp}``20``-`23`), which represents the _id_ of a <<key-rows,Key row>>.
If the track is known to be a remake, the non-zero <<artist-rows,Artist row>> _id_ of the original performer will be found at bytes{nbsp}``24``-`27` in __original_artist_id__.
If there is a known record label for the track, the non-zero value in __label_id__ (bytes{nbsp}``28``-`2b`) will link to the __id__ of a <<label-rows,Label row>> _id_.
Similarly, if there is a known remixer, there will be a non-zero value in __remixer_id__ (bytes{nbsp}``2c``-`2f`) linking to the _id_ of an <<artist-rows,Artist row>>.

The field _bitrate_ at bytes{nbsp}``30``-`33` stores the playback bit rate of the track, and __track_number__ at bytes{nbsp}``34``-`37` holds the position of the track within its album.
__tempo__ at bytes{nbsp}``38``-`3b` holds the playback tempo of the start of the track in beats per minute, multiplied by 100 (in order to support a precision of stem:[\frac{1}{100}] BPM).
If there is a known genre for the track, there will be a non-zero value in __genre_id__ at bytes{nbsp}``3c``-`3f`, representing the _id_ of a <<genre-rows,Genre row>>.

If the track is part of an album, there will be a non-zero value in __album_id__ at bytes{nbsp}``40``-`43`, and this will be the _id_ of an <<album-rows,Album row>>.
The <<artist-rows,Artist row>> _id_ of the primary performer associated with the track is found in __artist_id__ at bytes{nbsp}``44``-`47`.
And the _id_ of the track itself is found in _id_ at bytes{nbsp}``48``-`4b`.
If the album is known to consist of multiple discs, the disc number on which this track is found will be in __disc_number__ at bytes{nbsp}``4c``-`4d`.
And the number of times the track has been played is found in __play_count__ (bytes{nbsp}``4e``-`4f`).

The year in which the track was recorded, if known, is in _year_ at bytes{nbsp}``50``-`51`.
The sample depth of the track audio file (bits per sample) is in __sample_depth__ at bytes{nbsp}``52``-`53`.
The playback time of the track (in seconds, at normal speed) is in _duration_ at bytes{nbsp}``54``-`55`.
The purpose of the next two bytes, labeled _u~5~_, is unknown; they seem to always hold the value `29`.

Byte{nbsp}``58``, __color_id__ (labeled _c~id~_ in the diagram), holds the color assigned to the track in rekordbox, as the __id__ of a <<color-rows,Color row>>, or zero if no color has been assigned.
Byte{nbsp}``59``, _rating_ (labeled _r_ in the diagram) holds the rating (0 to 5 stars) assigned the track.

Bytes{nbsp}``60-``-``61``, _file_type_ (labeled _ft_ in the diagram) holds the format of the audio file:
* Unknown type: ``0x00``
* MP3: ``0x01``
* M4A: ``0x04``
* FLAC: ``0x05``
* WAV: ``0x0b``
* AIFF: ``0x0c``

The two bytes after them, labeled _u~7~_, hold the mysterious `3` which always seems to come before string offsets.
In this case, it takes up two bytes, since the track row uses sixteen bit offsets.

The rest of the track row is an array of 21 sixteen-bit offsets that point to <<devicesql-strings,DeviceSQL strings>>.
To find the start of the string, add the address of the start of the track row to the offset.
The purpose of each string is described in the following table.
For convenience, the strings can be accessed as Kaitai Struct instance values with the names shown in the table:

.Track offset strings.
[cols=">1,<3,<8"]
|===
|Index |Name |Content

|0 |__isrc__|International Standard Recording Code, if known, in <<isrc-strings,mangled format>>.footnote:evilfred[Thanks to https://github.com/evilfred[@evilfred] for discovering the ISRC strings and leading `00` byte in DeviceSQL UTF strings; we previously believed they were big-endian.]
|1 |_lyricist_|Lyricist of the track.
|2 |__unknown_string_2__|Unknown, contains an ASCII number.footnote:[Seems to increment when the track is re-exported, maybe some sort of version number.]
|3 |__unknown_string_3__|Unknown, contains an ASCII number or empty.
|4 |__unknown_string_4__|Unknown, “strange things” (as above).
|5 |_message_|Track message (a field in Rekordbox).
|6 |_publish_track_info_|"Publish track information" in Rekordbox, value is either "ON" or empty string.footnote:[Appears related to the Stagehand product to control DJ equipment remotely.]
|7 |__autoload_hotcues__|Empty or `"ON"`.footnote:[Apparently used rather than a simple bit flag to control whether hot cues are automatically loaded for the track.]
|8 |__unknown_string_5__|Unknown.
|9 |__unknown_string_6__|Unknown, usually empty.
|10|__date_added__|When the track was added to the rekordbox collection, YYYY-MM-DD.
|11|__release_date__|When the track was released, YYYY-MM-DD.
|12|__mix_name__|Name of the track remix, if any.
|13|__unknown_string_7__|Unknown, usually empty.
|14|__analyze_path__|File path of the xref:anlz.adoc[track analysis].
|15|__analyze_date__|When track analysis was performed, YYYY-MM-DD.
|16|_comment_|Track comment assigned by the DJ.
|17|_title_|Track title.
|18|__unknown_string_8__|Unknown, usually empty.
|19|_filename_|Name of track audio file.
|20|__file_path__|File path of track audio.
|===

[#devicesql-strings]
== DeviceSQL Strings

Many row types store string values, sometimes by directly embedding them, but more often by storing an offset to a location elsewhere in the heap.
In either case the string itself uses the structure described in this section.
Strings can be stored in a variety of formats.
The first byte of the structure seems to be a bunch of flags from which the format can be determined.
We are not certain of the details because not all formats are present in the export files we
have seen, so this represents our best guess so far.footnote:[Improved thanks to research by https://github.com/Swiftb0y[@Swiftboy], including finding https://bufferpool.quora.com/What-does-a-db-engine-string-look-like[this article] by the creator of DeviceSQL.]

[#long-string-interpretation]
.String format flags for long or wide strings
[bytefield]
----
include::example$bitfield.edn[]

(draw-box (text "E" :math))
(draw-box (text "A" :math))
(draw-box (text "N" :math))
(draw-box (text "W" :math))
(doseq [n (range 3)]
  (draw-box (text "u" :math [:sub n])))
(draw-box (text "S" :math))
----

Our best guess as to the interpretation of these bits follows:

[cols=">1l,2,8"]
|===
|bit |label |purpose

|7 |_E_ (endianness) |If set, the string seems to be little-endian
|6 |_A_ (ASCII)      |The string following is encoded in ASCII, endianness does not apply
|5 |_N_ (narrow)     |The contained string is encoded in UTF-8, endianness does not apply (not yet seen in practice though DeviceSQL claims to support encoding in ASCII, UTF-8, and UTF-16)
|4 |_W_ (wide)       |The contained string is encoded in UTF-16, endianness is determined by _E_
|0 |_S_ (short)      |If this bit is set, then the string is a <<short-string-interpretation,Short ASCII>> string, and the other "flag" bits in this byte actually store its length (see below)
|===

The details of this analysis are somewhat speculative because the only bit patterns we have seen in practice when S is zero are `0b01000000` for long-form ASCII strings and `0b10010000` for long-form `utf16le` strings (rekordbox probably just does not use the other supported string formats).

As described above, when S is `1`, we are dealing with a short ASCII string, and other flags are replaced by the seven-bit length field for the string field (including this type-and-length byte, so the string itself can be up to 126 characters long).

[#short-string-interpretation]
.Format flag and length for short ASCII strings
[bytefield]
----
include::example$bitfield.edn[]

(draw-box (text "length" :math) {:span 7})
(draw-box (hex-text 1 1))
----

[#short-ascii]
=== Short ASCII Strings

The flag byte described above is labeled _l~k~_ (_lengthAndKind_) below.
If _S_ (the low-order bit of _l~k~_) is set, it means the string field holds a short ASCII string.
The length of such a field can be extracted by right-shifting _l~k~_ once (or, equivalently,
dividing it by two).
This length is for the entire string field, including _l~k~_ itself, so the maximum length of actual string data is 126 bytes.

.Short ASCII DeviceSQL string.
[bytefield]
----
(draw-column-headers)
(draw-box (text "l" :math [:sub "k"]))
(draw-gap "ASCII data")
(draw-bottom)
----

NOTE: DeviceSQL strings do not have terminator bytes, so attempting to read more bytes than present can lead to garbage characters being present or crashing the parser for the more complex Unicode strings.
<<isrc-strings, ISRC Strings>> are the only exception.

[#long-strings]
=== Long Strings

Again the flag byte described above is labeled _l~k~_ (_lengthAndKind_) below.
If _S_ (the low-order bit of _l~k~_) is zero, it means the string field holds a long or wide string, whose format is specified by the other flag bits described <<long-string-interpretation,above>>, and whose length is determined by a two-byte _length_ field which follows the flag byte:

.Long DeviceSQL string.
[bytefield]
----
(draw-column-headers)
(draw-box (text "l" :math [:sub "k"]))
(draw-box (text "length" :math) {:span 2})
(draw-box (text "pad"))
(draw-gap "String data")
(draw-bottom)
----

As always, _length_ represents the length of the entire field including the header bytes, so the length of the actual string data is latexmath:[length - 4].
We have only ever seen zero values for the pad byte.
The encoding of the string data is determined by the flag bits in _l~k~_ as described <<long-string-interpretation,above>>.


[#isrc-strings]
=== ISRC Strings

When an International Standard Recording Code is present as the first string pointer in a track row, it is marked with kind `90` but does not actually hold a UTF-16-LE string.
Instead, the first byte after the `pad` value following the length is the value `03` and then there are latexmath:[length - 7] bytes of ASCII, followed by a null byte.
Crate Digger does not yet attempt to cope with this.
